### ISSUE TITLE
TenantProfileCacheRecords is null

### ISSUE THREAD

**Issue by ashikns** [AzureAD/microsoft-authentication-library-common-for-android#660] opened 2019-09-26 07:57 UTC
**Describe the bug**
Creation of LoadlAuthenticationResult fails at this line because _tenantProfileCacheRecords_ is null:

```
    final List<ICacheRecord> tenantProfileCacheRecords = brokerResult.getTenantProfileData();
    final LocalAuthenticationResult authenticationResult = new LocalAuthenticationResult(
                tenantProfileCacheRecords.get(0),
                tenantProfileCacheRecords,
                SdkType.MSAL
        );
```

I checked the response json used to create brokerResult and it **doesn't** have a tenant profile field.

 - Device: OnePlus 7
 - Android Version: 9
 - Browser: Using from a Unity app
 - MSAL Version: 1.0.0-RC9, Common @ 1.0.3

**To Reproduce**
Login to an Azure AD v2 app using a personal account. Potentially exists in other cases as well, but this is the only case I've tested till now, and kinda makes sense since a personal account doesn't have any tenant data associated with it?

Edit: Tried this with a work account and the same issue exists :(

**Comment by ashikns** [comment] 2019-09-26 11:08
On further investigation this only happens when a broker app is present. I solved it by setting "broker_redirect_uri_registered" to false in config. On a side note, the name of the field makes me think there's some redirect uri I'm supposed to register?

**Comment by iambmelt** [comment] 2019-09-26 20:30
@ashikns What version of Company Portal / Authenticator are you using? Would like to repro on my end

**Comment by ashikns** [comment] 2019-09-27 03:14
Microsoft Authenticator version 6.6.3 with one personal and one work account setup. Msal built as localRelease @ ecbe6aa7fb1daa7bb7de1f9c03db7da261485f58, common @ b618219885b86f1c4f4bf84854a24bb178885b1b.

Note that the app is a Unity app built for android (version 2019.1.14f1, built on mono backend). I'll explain the setup in case it's relevant:

1. Msal built as mentioned above, but I add a createMultiplePCA function that accepts InputStream directly.
2. A native android library project that consumes msal and provides a wrapper for it that Unity can interface with.
3. Pca is created by passing UnityMainActivity.getAppContext().

**Comment by iambmelt** [comment] 2019-12-16 20:17
Closing as this appears to caused by combining unsupported versions: pre-release MSAL w/ TenantProfile support + broker versions that do not support it

Feel free to comment-back if you continue to have issues and we can investigate

**Closed by iambmelt** 2019-12-16 20:17 UTC
